version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/assets
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=9y22zfz_$-5d=+2)s^c=ftr4bo&l5_1g%=y4xhf1f*#j*bnhd6
        - EMAIL_HOST = 'xxx'
        - EMAIL_PORT = 465
        - EMAIL_HOST_USER = 'xxx'
        - EMAIL_HOST_PASSWORD = 'xxx'
        - EMAIL_USE_SSL = True


    depends_on: []

volumes:
  static_volume:
    driver: local
  media_volume:
    driver: local
