from django.urls import path
from . import views

urlpatterns = [
    path('Index', views.Index, name='Index'),
    path('', views.Login, name='Login'),
    path('register', views.register, name='register'),
#    path('Admin', views.Admin, name='Admin'),
    path('Dashboard', views.Dashboard, name='Dashboard'),
    path('Contact', views.Contact, name='Contact'),
    path('Complaint', views.Complaint, name='Complaint'),
    path('carry99', views.carry99, name='carry99'),
    path('kisan_shakti_kendra', views.kisan_shakti_kendra, name='kisan_shakti_kendra'),
    path('mobileperks', views.mobileperks, name='mobileperks'),
    path('onlineCampaign', views.onlineCampaign, name='onlineCampaign'),
    path('form', views.form, name='form'),
    path('about', views.about, name='about'),
    path('insurance', views.insurance, name='insurance'),
    path('campaign/<int:sno>', views.campaign, name='campaign'),
    path('coming_soon', views.coming_soon, name='coming_soon'),
    path('Health_insurance', views.Health_insurance, name='Health_insurance'),
    path('Life_insurance', views.Life_insurance, name='Life_insurance'),
    path('Motor_insurance', views.Motor_insurance, name='Motor_insurance'),
    path('Fire_insurance', views.Fire_insurance, name='Fire_insurance'),
    path('Liability_insurance', views.Liability_insurance, name='Liability_insurance'),
    path('Marine_insurance', views.Marine_insurance, name='Marine_insurance'),
    path('A&H_insurance', views.AH_insurance, name='A&H_insurance'),
    path('securecare', views.securecare, name='securecare'),
    path('apkeducation', views.apkeducation, name='apkeducation'),
    path('logout_user', views.logout_user, name='logout_user'),
    path('campaign_form', views.campaign_form, name='campaign_form'),
    path('otp', views.otp, name='otp'),
    path('report/<str:date>/', views.report, name='report'),
    path('verify_detail', views.verify_detail, name='verify_detail'),
    path('verify_details', views.verify_details, name='verify_details'),
    path('register_otp', views.register_otp, name='register_otp'),
    path('new_password', views.new_password, name='new_password'),
    path('credit_card', views.credit_card, name='credit_card'),
    path('account_opening', views.account_opening, name='account_opening'),
    path('CreditCard', views.CreditCard, name='CreditCard'),
    ]
